### ISSUE TITLE
com.alipay.sofa.hessian对hessian的源码进行了改造，直接在hessian的源码中引用阿里内部扩展的类，这种改造方式是不是不太友好，导致其他模块依赖的hessian无法使用。

### ISSUE THREAD

**Issue by tianshouzhi** [alipay/sofa-bolt#122]
Caused by: java.lang.NoSuchMethodError: com.caucho.hessian.io.SerializerFactory.setClassNameResolver(Lcom/alipay/hessian/ClassNameResolver;)V
	at com.alipay.remoting.serialization.HessianSerializer.<init>(HessianSerializer.java:44)
	at com.alipay.remoting.serialization.SerializerManager.<clinit>(SerializerManager.java:36)
	at com.meituan.swan.remoting.rpc.sofa.RemotingBoltClient.<clinit>(RemotingBoltClient.java:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)

**Comment by khotyn** [comment]
@leizhiyuan 帮忙看下哦~~

**Comment by leizhiyuan** [comment]
@tianshouzhi 你们自己只使用bolt组件还是使用sofaboot？

**Comment by leizhiyuan** [comment]
```
<dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>hessian</artifactId>
            <version>${hessian.version}</version>
            <scope>provided</scope>
        </dependency>
```

com.alipay.remoting.serialization.HessianSerializer#HessianSerializer

```
 public HessianSerializer() {
        //initialize with default black list in hessian
        ClassNameResolver resolver = new ClassNameResolver();
        resolver.addFilter(new InternalNameBlackListFilter(8192));
        serializerFactory.setClassNameResolver(resolver);
    }
```

这个地方，如果要改，建议 bolt改一下，如果监测到ClassNameResolver这个类不存在，说明不是我们的hessian，就不要设置这段代码了。

**Comment by khotyn** [comment]
cc @dbl-x

**Comment by dbl-x** [comment]
@tianshouzhi 目前sofa-bolt对sofa-hessian是强依赖，sofa-hessian也是开源的，能引用到，并不会存在问题。另外，sofa-hessian也是对hessian做了很多优化的，所以建议你可以使用sofa-hessian。

你的场景是使用sofa-bolt但是必须使用原生的hessian，不能使用sofa-hessian吗？

**Comment by tianshouzhi** [comment]
> @tianshouzhi 你们自己只使用bolt组件还是使用sofaboot？
> 
> 你们想使用bolt，但是使用自己的hessian？

只使用bolt，hessian使用自己的

**Comment by tianshouzhi** [comment]
> @tianshouzhi 你们自己只使用bolt组件还是使用sofaboot？
> 
> 你们想使用bolt，但是使用自己的hessian？

**Comment by tianshouzhi** [comment]
改造没有什么问题，主要是不想自己维护，后面你们这边如果有升级的话，我还得跟着合并你们的最新修改，不方便。我现在做的是一个基础组件，只需要依赖sofa-bolt就行了。并且我司还有其他组件，也会使用hessian，担心也会有冲突。

**Comment by tianshouzhi** [comment]
建议给用户提供一个选择使用sofa-hessian，还是原生hessian的机会。

**Comment by dbl-x** [comment]
> 建议给用户提供一个选择使用sofa-hessian，还是原生hessian的机会。

@tianshouzhi 好的，我们会考虑把这个做到bolt的下一个版本中的，谢谢你的建议。

**Comment by dbl-x** [comment]
release in version 1.5.3: https://github.com/alipay/sofa-bolt/releases/tag/v1.5.3
