### ISSUE TITLE
threadpools shutdown problems

### ISSUE THREAD

**Issue by xmtsui** [alipay/sofa-bolt#14]
@killme2008 point out some threadpools ( netty eventloop etc.) do not shutdown after client or server shutdown

**Comment by yangl** [comment]
import com.alipay.remoting.AsyncContext;
import com.alipay.remoting.BizContext;
import com.alipay.remoting.exception.RemotingException;
import com.alipay.remoting.rpc.RpcClient;
import com.alipay.remoting.rpc.RpcResponseFuture;
import com.alipay.remoting.rpc.RpcServer;
import com.alipay.remoting.rpc.protocol.AbstractUserProcessor;

public class BoltTest {

    public static void main(String[] args) {

        RpcServer server = new RpcServer(18080, true, true);
        server.registerUserProcessor(new AbstractUserProcessor<String>() {
            @Override
            public void handleRequest(BizContext bizCtx, AsyncContext asyncCtx, String request) {
                System.out.println("[服务端Async]收到数据<<<<----" + request + " remoteAddress: " + bizCtx.getRemoteAddress() + " remoteHost: " + bizCtx.getRemoteHost() + " remotePort:" + bizCtx.getRemotePort());

                asyncCtx.sendResponse("服务端Async返回数据---->>>>" + request);
            }

            @Override
            public Object handleRequest(BizContext bizCtx, String request) throws Exception {
                System.out.println("[服务端Sync]收到数据<<<<----" + request + " remoteAddress: " + bizCtx.getRemoteAddress() + " remoteHost: " + bizCtx.getRemoteHost() + " remotePort:" + bizCtx.getRemotePort());

                return "服务端Sync返回数据---->>>>" + request;
            }

            @Override
            public String interest() {
                return String.class.getName();
            }
        });

        server.start();


        RpcClient client = new RpcClient();
        client.init();
        try {

            String addr = "127.0.0.1:18080?_PROTOCOL=2&_VERSION=2";

            client.oneway(addr, "hi, bolt oneway!");

            String s = (String) client.invokeSync(addr, "hi, bolt sync!", 100);
            System.out.println("[客户端]Sync方式收到数据  " + s);


            RpcResponseFuture f = client.invokeWithFuture(addr, "hi, bolt future!", 100);
            System.out.println("[客户端]Future方式收到数据  " + f.get(10));


        } catch (RemotingException | InterruptedException e) {
            e.printStackTrace();
        }


        client.shutdown();

        server.stop();

    }
}



[服务端Sync]收到数据<<<<----hi, bolt oneway! remoteAddress: 127.0.0.1:50683 remoteHost: 127.0.0.1 remotePort:50683
[服务端Sync]收到数据<<<<----hi, bolt sync! remoteAddress: 127.0.0.1:50683 remoteHost: 127.0.0.1 remotePort:50683
[客户端]Sync方式收到数据  服务端Sync返回数据---->>>>hi, bolt sync!
[服务端Sync]收到数据<<<<----hi, bolt future! remoteAddress: 127.0.0.1:50683 remoteHost: 127.0.0.1 remotePort:50683
[客户端]Future方式收到数据  服务端Sync返回数据---->>>>hi, bolt future!
2018-05-18 11:02:47
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode):

"DestroyJavaVM" #26 prio=5 os_prio=0 tid=0x000000002061c800 nid=0x2104 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Bolt-default-executor-5-thread-5" #24 prio=5 os_prio=0 tid=0x000000002061b000 nid=0x2c3c waiting on condition [0x00000000215bf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c08f5f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Bolt-default-executor-5-thread-4" #23 prio=5 os_prio=0 tid=0x000000002061a800 nid=0x2a7c waiting on condition [0x0000000021ecf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c08f5f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"DefaultTimer10-8-thread-1" #22 prio=5 os_prio=0 tid=0x0000000020619800 nid=0x2978 waiting on condition [0x0000000021cdf000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
	at java.lang.Thread.run(Thread.java:748)

"Bolt-default-executor-5-thread-3" #21 prio=5 os_prio=0 tid=0x000000002048a000 nid=0x1998 waiting on condition [0x0000000021ace000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c08f5f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Bolt-default-executor-5-thread-2" #20 prio=5 os_prio=0 tid=0x0000000020493800 nid=0x2ae0 waiting on condition [0x000000002195e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c08f5f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Bolt-default-executor-5-thread-1" #19 prio=5 os_prio=0 tid=0x000000002046b800 nid=0x16f0 waiting on condition [0x00000000217ef000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c08f5f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Bolt-conn-event-executor-7-thread-1" #17 prio=5 os_prio=0 tid=0x000000002023e800 nid=0x2f8c waiting on condition [0x00000000216ef000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c74b568> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Bolt-conn-event-executor-3-thread-1" #18 prio=5 os_prio=0 tid=0x000000002023d800 nid=0x2eec waiting on condition [0x000000002118f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076bf8c860> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Rpc-netty-server-worker-1-thread-1" #16 prio=5 os_prio=0 tid=0x0000000020233800 nid=0x1b2c runnable [0x00000000212ae000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000076be95ff0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000076bbe6310> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000076bbe3de8> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"Rpc-netty-client-worker-6-thread-1" #15 prio=5 os_prio=0 tid=0x0000000020206000 nid=0x2590 runnable [0x000000001f97f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000076c6f97a0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000076c6f5d10> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000076c6f5bc0> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #11 daemon prio=9 os_prio=0 tid=0x000000001dfd4000 nid=0x2e2c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #10 daemon prio=9 os_prio=2 tid=0x000000001ded6000 nid=0x2470 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x000000001decd000 nid=0x2fec waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x000000001dec8000 nid=0x2f80 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x000000001de88000 nid=0x2cf0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Ctrl-Break" #6 daemon prio=5 os_prio=0 tid=0x000000001de86800 nid=0x2ac8 runnable [0x000000001f66e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000076b4db640> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x000000076b4db640> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:64)

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000001ddf9000 nid=0x18f4 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000001ddf8000 nid=0x2a3c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000001cd2f000 nid=0x19e0 in Object.wait() [0x000000001edee000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076b208ec0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000076b208ec0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:212)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x000000001cd28800 nid=0x145c in Object.wait() [0x000000001f07e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076b206b68> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000076b206b68> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=2 tid=0x000000001dd92000 nid=0x2f04 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002b2e000 nid=0x548 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002b2f800 nid=0x199c runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002b31000 nid=0x100c runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002b32800 nid=0x1b08 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x0000000002b36800 nid=0x2d78 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x0000000002b37800 nid=0x2e34 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x0000000002b3a800 nid=0x1274 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x0000000002b3c000 nid=0x2ba8 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x000000001e014800 nid=0x12e4 waiting on condition 

JNI global references: 318

Heap
 PSYoungGen      total 76288K, used 40724K [0x000000076b200000, 0x0000000770700000, 0x00000007c0000000)
  eden space 65536K, 62% used [0x000000076b200000,0x000000076d9c5228,0x000000076f200000)
  from space 10752K, 0% used [0x000000076fc80000,0x000000076fc80000,0x0000000770700000)
  to   space 10752K, 0% used [0x000000076f200000,0x000000076f200000,0x000000076fc80000)
 ParOldGen       total 175104K, used 0K [0x00000006c1600000, 0x00000006cc100000, 0x000000076b200000)
  object space 175104K, 0% used [0x00000006c1600000,0x00000006c1600000,0x00000006cc100000)
 Metaspace       used 10357K, capacity 10530K, committed 10624K, reserved 1058816K
  class space    used 1287K, capacity 1337K, committed 1408K, reserved 1048576K

**Comment by yangl** [comment]
1.Netty的workerGroup调用下shutdownGracefully()；
ConnectionFactory接口 RpcConnectionFactory类暴露shutdown方法：
`
@Override
    public void shutdown() {
        workerGroup.shutdownGracefully();
    }
`
然后RpcClient的shutdown方法里调用上边方法即可：
`
       if (connctionFactory != null) {
            connctionFactory.shutdown();
        }
`
2.线程池Bolt-conn-event-executor及Bolt-conn-event-executor设置成daemon即可；

另，项目好像没有统一使用AlipayFormatter.xml格式化代码，格式化一下修改的文件差异太多就不PR了！

**Comment by khotyn** [comment]
@yangl 介意帮忙单独提一个 Formatter 的 PR 吗？然后根据这个 PR 后的结果，再提这个问题的 PR 就行了。

**Comment by yangl** [comment]
@khotyn  已提交，invokeWithFuture及invokeWithCallback方式 主进程退出要稍等会，大概20秒的样子，不是立马就退出，invokeSync及oneway会立马就退出了！  https://github.com/alipay/sofa-bolt/pull/31

**Comment by xmtsui** [comment]
@yangl 赞，我来看下pr哈。  

另外，如线下沟通，formatter是有的，format配置的`${user.dir}/.AlipayFormatter.xml` windows下用户识别不到。sofa rpc等可能都有类似的问题。@khotyn

**Comment by yangl** [comment]
@xmtsui   formatter是路径配置有问题哈，**${user.dir}**/.AlipayFormatter.xml应该是user.dir改成project.basedir就好了。阿里外部同学家目录下是没有这个formatter文件的。

**Comment by ujjboy** [comment]
@yangl @xmtsui 

${user.dir} 是指当前工作目录，${user.home} 才是用户的Home目录。

例如我在 `~/workspace/sofa-bolt` 下执行 `mvn`，那 `${usr.dir}` 应该就是 `~/workspace/sofa-bolt`。 我试了下 Windows 下是可以拿到这个地址的。

不过改成 `${project.basedir}` 的话更好一点，就依赖 maven 自己的工程目录结构。

**Comment by xmtsui** [comment]
> 阿里外部同学家目录下是没有这个formatter文件的。
@yangl 嗯，这个知道的，所以代码里自身就加了formatter。在代码目录的`.middleware-common`目录下`。

**Comment by xmtsui** [comment]
@yangl 参考@ujjbody 的回复，当时你mvn的时候，是不是不在sofa-bolt的代码根目录下。

**Comment by yangl** [comment]
嗯，user.dir命令执行的当前目录，相对路径，IDEA开发工具下执行就可能就找不到这个文件了
